### ISSUE TITLE
[Game]: Grand Theft Auto V (Xbox One)

### ISSUE THREAD

**Issue by Dragonfyre08** [ItsLogic/Xbox-Achievement-Unlocker#126] opened 2024-04-26 08:58 UTC
### Confirmation

- [X] I have verified that this is not a duplicate request.

### Game Link

https://www.trueachievements.com/game/Grand-Theft-Auto-V-Xbox-One/achievements

### Game Platform

Console only

### Additional Game Information

All achievements

**Comment by ItsLogic** [comment] 2024-06-17 09:54
dupe of #106

**Closed as not planned by ItsLogic** 2024-06-17 09:54 UTC
Labels: Game
