### ISSUE TITLE
game

### ISSUE THREAD

**Issue by hello72823** [ItsLogic/Xbox-Achievement-Unlocker#303] opened 2024-07-21 01:38 UTC
### Confirmation

- [X] I have verified that this is not a duplicate request.

### Game Link

https://www.xbox.com/pt-BR/games/gta-v#purchaseoptions

### Game Platform

Console only

### Additional Game Information

Hello, good night or day, I would like to know if you could do it in GTA 5 or in State of Decay 2 Farcry 4 Assassis Creed Black Flag and Call of Duty I know I'm asking for many more, I really like your work and I know you can do it since Thank you in advance

**Comment by VeryOriginalUsername2025** [comment] 2024-07-21 11:32
dupe of https://github.com/Fumo-Unlockers/Xbox-Achievement-Unlocker/issues/177

still invalid.

**Closed as not planned** 2024-07-21 14:28 UTC
Labels: Game
