### ISSUE TITLE
[Game]: Grand Theft Auto V (Xbox One) [Online]

### ISSUE THREAD

**Issue by drakarch** [ItsLogic/Xbox-Achievement-Unlocker#279] opened 2024-06-17 09:15 UTC
### Confirmation

- [X] I have verified that this is not a duplicate request.

### Game Link

https://www.trueachievements.com/game/Grand-Theft-Auto-V-Xbox-One/achievements

### Game Platform

Console only

### Additional Game Information

Elitist:
GTA Online: Complete all 3 Elite Challenges in The Doomsday Heist.
Only 0.01% of gamers unlocked this 

Masterminds:
GTA Online: Complete all 3 Criminal Mastermind challenges in The Doomsday Heist.
Only 0.01% of gamers unlocked this

**Comment by ItsLogic** [comment] 2024-06-17 09:54
dupe of #106

**Closed as not planned by ItsLogic** 2024-06-17 09:54 UTC
Labels: Game
