### ISSUE TITLE
[Feature-Request]: games that dont work to the unlocker

### ISSUE THREAD

**Issue by mickygamer44** [ItsLogic/Xbox-Achievement-Unlocker#53] opened 2023-08-07 05:08 UTC
### Tool Section

Unlocker

### What feature are you requesting?

there are some games that the unlocker does not work on some games such as dying light 2, dying light 1, vikings wolves of midgard etc.....     do you think you can update them? so that we can unlock the achievements? thanks

**Comment by ItsLogic** [comment] 2023-08-07 05:18
duplicate of #2

**Closed by ItsLogic** 2023-08-07 05:18 UTC
Labels: enhancement
