### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by XbotZZ** [ItsLogic/Xbox-Achievement-Unlocker#46] opened 2023-06-14 19:09 UTC
### What version of the app were you running?

1.7

### Winver

Win10

### Have I checked if the bug was reported?

Yes

### What is the bug?

Since the last update i keep getting error message when i try to use it "something did a fucky wucky and i don't have specific message for the error code" ^^' (i try many time before posting the fuckywucky fixer ^^ )

**Comment by ItsLogic** [comment] 2023-06-14 19:10
What are you clicking when the error shows?

**Comment by HellAleX92** [comment] 2023-06-15 20:10
MS Achievement Servers are down today again. This is why all versions of this tool will not work as intended.
It's no bug on itself, it's a massive problem at MS.

**Comment by siciliansinner** [comment] 2023-06-16 00:02
thank you for the reply HellAleX92, as of the past hour i can get it to sometimes work again. Must be on MS end like you are saying.

**Comment by ItsLogic** [comment] 2023-06-25 22:45
closing this as microsoft servers just suck. Not really sure how to handle them sucking on the app side so ill just leave it as is

**Closed by ItsLogic** 2023-06-25 22:45 UTC
Labels: bug
