### ISSUE TITLE
[Game]: Forza Horizon 2 XONE

### ISSUE THREAD

**Issue by gta006eflc** [ItsLogic/Xbox-Achievement-Unlocker#178] opened 2024-05-05 14:46 UTC
### Confirmation

- [X] I have verified that this is not a duplicate request.

### Game Link

https://www.trueachievements.com/game/Forza-Horizon-2/achievements?gamerid=670016

### Game Platform

Console only

### Additional Game Information

this game have server off and is verry long to play and have a 16 achivements discontinued this is great game :) old but great and soundtrack is great too 
sorry for my english

**Comment by ItsLogic** [comment] 2024-06-05 01:20
duplicate of #107

**Closed as completed by ItsLogic** 2024-06-05 01:20 UTC
Labels: Game
