### ISSUE TITLE
[Game]: Titanfall

### ISSUE THREAD

**Issue by werewookiee7** [ItsLogic/Xbox-Achievement-Unlocker#141] opened 2024-04-26 13:22 UTC
### Confirmation

- [X] I have verified that this is not a duplicate request.

### Game Link

https://www.trueachievements.com/game/Titanfall/achievements

### Game Platform

Console only

### Additional Game Information

Two's Good, but I Want Three
All Day Every Day

**Comment by ItsLogic** [comment] 2024-04-26 14:23
Dupe of #101

**Closed as not planned** 2024-04-26 14:24 UTC
Labels: Game
